export enum CART_ACTION_TYPES {
  SET_IS_CART_OPEN = 'cart/SET_IS_CART_OPEN',
  SET_CART_ITEMS = 'cart/SET_CART_ITEMS',
  SET_ITEMS_QUANTITY = 'cart/SET_ITEMS_QUANTITY',
  SET_TOTAL_PRICE = 'cart/SET_TOTAL_PRICE',
};
